// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.8.3
//   protoc               v3.21.12
// source: proto/feed/feed.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import type { CallContext, CallOptions } from "nice-grpc-common";
import { Empty } from "../../google/protobuf/empty";
import { Timestamp } from "../../google/protobuf/timestamp";

export const protobufPackage = "feed";

export interface UpdateFeedPreferencesRequest {
  interestPrompt: string;
  feedEnabled: boolean;
}

export interface FeedPreferencesResponse {
  interestPrompt: string;
  feedEnabled: boolean;
}

export interface GetDailyFeedRequest {
  /** Date in YYYY-MM-DD format */
  date: string;
}

export interface Article {
  id: string;
  title: string;
  url: string;
  snippet: string;
  relevanceScore: number;
  createdAt: Date | undefined;
}

export interface GetDailyFeedResponse {
  date: string;
  articles: Article[];
}

export interface GetFeedCalendarStatusRequest {
  /** Month in YYYY-MM format, defaults to current month */
  month: string;
}

export interface CalendarDay {
  date: string;
  articleCount: number;
}

export interface GetFeedCalendarStatusResponse {
  days: CalendarDay[];
}

function createBaseUpdateFeedPreferencesRequest(): UpdateFeedPreferencesRequest {
  return { interestPrompt: "", feedEnabled: false };
}

export const UpdateFeedPreferencesRequest: MessageFns<UpdateFeedPreferencesRequest> = {
  encode(message: UpdateFeedPreferencesRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.interestPrompt !== "") {
      writer.uint32(10).string(message.interestPrompt);
    }
    if (message.feedEnabled !== false) {
      writer.uint32(16).bool(message.feedEnabled);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UpdateFeedPreferencesRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUpdateFeedPreferencesRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.interestPrompt = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.feedEnabled = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): UpdateFeedPreferencesRequest {
    return {
      interestPrompt: isSet(object.interestPrompt) ? globalThis.String(object.interestPrompt) : "",
      feedEnabled: isSet(object.feedEnabled) ? globalThis.Boolean(object.feedEnabled) : false,
    };
  },

  toJSON(message: UpdateFeedPreferencesRequest): unknown {
    const obj: any = {};
    if (message.interestPrompt !== "") {
      obj.interestPrompt = message.interestPrompt;
    }
    if (message.feedEnabled !== false) {
      obj.feedEnabled = message.feedEnabled;
    }
    return obj;
  },

  create(base?: DeepPartial<UpdateFeedPreferencesRequest>): UpdateFeedPreferencesRequest {
    return UpdateFeedPreferencesRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<UpdateFeedPreferencesRequest>): UpdateFeedPreferencesRequest {
    const message = createBaseUpdateFeedPreferencesRequest();
    message.interestPrompt = object.interestPrompt ?? "";
    message.feedEnabled = object.feedEnabled ?? false;
    return message;
  },
};

function createBaseFeedPreferencesResponse(): FeedPreferencesResponse {
  return { interestPrompt: "", feedEnabled: false };
}

export const FeedPreferencesResponse: MessageFns<FeedPreferencesResponse> = {
  encode(message: FeedPreferencesResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.interestPrompt !== "") {
      writer.uint32(10).string(message.interestPrompt);
    }
    if (message.feedEnabled !== false) {
      writer.uint32(16).bool(message.feedEnabled);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): FeedPreferencesResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseFeedPreferencesResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.interestPrompt = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.feedEnabled = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): FeedPreferencesResponse {
    return {
      interestPrompt: isSet(object.interestPrompt) ? globalThis.String(object.interestPrompt) : "",
      feedEnabled: isSet(object.feedEnabled) ? globalThis.Boolean(object.feedEnabled) : false,
    };
  },

  toJSON(message: FeedPreferencesResponse): unknown {
    const obj: any = {};
    if (message.interestPrompt !== "") {
      obj.interestPrompt = message.interestPrompt;
    }
    if (message.feedEnabled !== false) {
      obj.feedEnabled = message.feedEnabled;
    }
    return obj;
  },

  create(base?: DeepPartial<FeedPreferencesResponse>): FeedPreferencesResponse {
    return FeedPreferencesResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<FeedPreferencesResponse>): FeedPreferencesResponse {
    const message = createBaseFeedPreferencesResponse();
    message.interestPrompt = object.interestPrompt ?? "";
    message.feedEnabled = object.feedEnabled ?? false;
    return message;
  },
};

function createBaseGetDailyFeedRequest(): GetDailyFeedRequest {
  return { date: "" };
}

export const GetDailyFeedRequest: MessageFns<GetDailyFeedRequest> = {
  encode(message: GetDailyFeedRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.date !== "") {
      writer.uint32(10).string(message.date);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetDailyFeedRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetDailyFeedRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.date = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetDailyFeedRequest {
    return { date: isSet(object.date) ? globalThis.String(object.date) : "" };
  },

  toJSON(message: GetDailyFeedRequest): unknown {
    const obj: any = {};
    if (message.date !== "") {
      obj.date = message.date;
    }
    return obj;
  },

  create(base?: DeepPartial<GetDailyFeedRequest>): GetDailyFeedRequest {
    return GetDailyFeedRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<GetDailyFeedRequest>): GetDailyFeedRequest {
    const message = createBaseGetDailyFeedRequest();
    message.date = object.date ?? "";
    return message;
  },
};

function createBaseArticle(): Article {
  return { id: "", title: "", url: "", snippet: "", relevanceScore: 0, createdAt: undefined };
}

export const Article: MessageFns<Article> = {
  encode(message: Article, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.title !== "") {
      writer.uint32(18).string(message.title);
    }
    if (message.url !== "") {
      writer.uint32(26).string(message.url);
    }
    if (message.snippet !== "") {
      writer.uint32(34).string(message.snippet);
    }
    if (message.relevanceScore !== 0) {
      writer.uint32(45).float(message.relevanceScore);
    }
    if (message.createdAt !== undefined) {
      Timestamp.encode(toTimestamp(message.createdAt), writer.uint32(50).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Article {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseArticle();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.title = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.url = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.snippet = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 45) {
            break;
          }

          message.relevanceScore = reader.float();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.createdAt = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Article {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : "",
      title: isSet(object.title) ? globalThis.String(object.title) : "",
      url: isSet(object.url) ? globalThis.String(object.url) : "",
      snippet: isSet(object.snippet) ? globalThis.String(object.snippet) : "",
      relevanceScore: isSet(object.relevanceScore) ? globalThis.Number(object.relevanceScore) : 0,
      createdAt: isSet(object.createdAt) ? fromJsonTimestamp(object.createdAt) : undefined,
    };
  },

  toJSON(message: Article): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    if (message.title !== "") {
      obj.title = message.title;
    }
    if (message.url !== "") {
      obj.url = message.url;
    }
    if (message.snippet !== "") {
      obj.snippet = message.snippet;
    }
    if (message.relevanceScore !== 0) {
      obj.relevanceScore = message.relevanceScore;
    }
    if (message.createdAt !== undefined) {
      obj.createdAt = message.createdAt.toISOString();
    }
    return obj;
  },

  create(base?: DeepPartial<Article>): Article {
    return Article.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<Article>): Article {
    const message = createBaseArticle();
    message.id = object.id ?? "";
    message.title = object.title ?? "";
    message.url = object.url ?? "";
    message.snippet = object.snippet ?? "";
    message.relevanceScore = object.relevanceScore ?? 0;
    message.createdAt = object.createdAt ?? undefined;
    return message;
  },
};

function createBaseGetDailyFeedResponse(): GetDailyFeedResponse {
  return { date: "", articles: [] };
}

export const GetDailyFeedResponse: MessageFns<GetDailyFeedResponse> = {
  encode(message: GetDailyFeedResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.date !== "") {
      writer.uint32(10).string(message.date);
    }
    for (const v of message.articles) {
      Article.encode(v!, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetDailyFeedResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetDailyFeedResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.date = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.articles.push(Article.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetDailyFeedResponse {
    return {
      date: isSet(object.date) ? globalThis.String(object.date) : "",
      articles: globalThis.Array.isArray(object?.articles) ? object.articles.map((e: any) => Article.fromJSON(e)) : [],
    };
  },

  toJSON(message: GetDailyFeedResponse): unknown {
    const obj: any = {};
    if (message.date !== "") {
      obj.date = message.date;
    }
    if (message.articles?.length) {
      obj.articles = message.articles.map((e) => Article.toJSON(e));
    }
    return obj;
  },

  create(base?: DeepPartial<GetDailyFeedResponse>): GetDailyFeedResponse {
    return GetDailyFeedResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<GetDailyFeedResponse>): GetDailyFeedResponse {
    const message = createBaseGetDailyFeedResponse();
    message.date = object.date ?? "";
    message.articles = object.articles?.map((e) => Article.fromPartial(e)) || [];
    return message;
  },
};

function createBaseGetFeedCalendarStatusRequest(): GetFeedCalendarStatusRequest {
  return { month: "" };
}

export const GetFeedCalendarStatusRequest: MessageFns<GetFeedCalendarStatusRequest> = {
  encode(message: GetFeedCalendarStatusRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.month !== "") {
      writer.uint32(10).string(message.month);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetFeedCalendarStatusRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetFeedCalendarStatusRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.month = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetFeedCalendarStatusRequest {
    return { month: isSet(object.month) ? globalThis.String(object.month) : "" };
  },

  toJSON(message: GetFeedCalendarStatusRequest): unknown {
    const obj: any = {};
    if (message.month !== "") {
      obj.month = message.month;
    }
    return obj;
  },

  create(base?: DeepPartial<GetFeedCalendarStatusRequest>): GetFeedCalendarStatusRequest {
    return GetFeedCalendarStatusRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<GetFeedCalendarStatusRequest>): GetFeedCalendarStatusRequest {
    const message = createBaseGetFeedCalendarStatusRequest();
    message.month = object.month ?? "";
    return message;
  },
};

function createBaseCalendarDay(): CalendarDay {
  return { date: "", articleCount: 0 };
}

export const CalendarDay: MessageFns<CalendarDay> = {
  encode(message: CalendarDay, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.date !== "") {
      writer.uint32(10).string(message.date);
    }
    if (message.articleCount !== 0) {
      writer.uint32(16).int32(message.articleCount);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CalendarDay {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCalendarDay();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.date = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.articleCount = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CalendarDay {
    return {
      date: isSet(object.date) ? globalThis.String(object.date) : "",
      articleCount: isSet(object.articleCount) ? globalThis.Number(object.articleCount) : 0,
    };
  },

  toJSON(message: CalendarDay): unknown {
    const obj: any = {};
    if (message.date !== "") {
      obj.date = message.date;
    }
    if (message.articleCount !== 0) {
      obj.articleCount = Math.round(message.articleCount);
    }
    return obj;
  },

  create(base?: DeepPartial<CalendarDay>): CalendarDay {
    return CalendarDay.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<CalendarDay>): CalendarDay {
    const message = createBaseCalendarDay();
    message.date = object.date ?? "";
    message.articleCount = object.articleCount ?? 0;
    return message;
  },
};

function createBaseGetFeedCalendarStatusResponse(): GetFeedCalendarStatusResponse {
  return { days: [] };
}

export const GetFeedCalendarStatusResponse: MessageFns<GetFeedCalendarStatusResponse> = {
  encode(message: GetFeedCalendarStatusResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.days) {
      CalendarDay.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetFeedCalendarStatusResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetFeedCalendarStatusResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.days.push(CalendarDay.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetFeedCalendarStatusResponse {
    return { days: globalThis.Array.isArray(object?.days) ? object.days.map((e: any) => CalendarDay.fromJSON(e)) : [] };
  },

  toJSON(message: GetFeedCalendarStatusResponse): unknown {
    const obj: any = {};
    if (message.days?.length) {
      obj.days = message.days.map((e) => CalendarDay.toJSON(e));
    }
    return obj;
  },

  create(base?: DeepPartial<GetFeedCalendarStatusResponse>): GetFeedCalendarStatusResponse {
    return GetFeedCalendarStatusResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<GetFeedCalendarStatusResponse>): GetFeedCalendarStatusResponse {
    const message = createBaseGetFeedCalendarStatusResponse();
    message.days = object.days?.map((e) => CalendarDay.fromPartial(e)) || [];
    return message;
  },
};

export interface FeedServiceImplementation<CallContextExt = {}> {
  /** Update user's feed preferences (interest prompt and enable/disable) */
  updateFeedPreferences(
    request: UpdateFeedPreferencesRequest,
    context: CallContext & CallContextExt,
  ): Promise<DeepPartial<Empty>>;
  /** Get user's current feed preferences */
  getFeedPreferences(
    request: Empty,
    context: CallContext & CallContextExt,
  ): Promise<DeepPartial<FeedPreferencesResponse>>;
  /** Get articles for a specific date */
  getDailyFeed(
    request: GetDailyFeedRequest,
    context: CallContext & CallContextExt,
  ): Promise<DeepPartial<GetDailyFeedResponse>>;
  /** Get dates that have articles for the calendar view */
  getFeedCalendarStatus(
    request: GetFeedCalendarStatusRequest,
    context: CallContext & CallContextExt,
  ): Promise<DeepPartial<GetFeedCalendarStatusResponse>>;
}

export interface FeedServiceClient<CallOptionsExt = {}> {
  /** Update user's feed preferences (interest prompt and enable/disable) */
  updateFeedPreferences(
    request: DeepPartial<UpdateFeedPreferencesRequest>,
    options?: CallOptions & CallOptionsExt,
  ): Promise<Empty>;
  /** Get user's current feed preferences */
  getFeedPreferences(
    request: DeepPartial<Empty>,
    options?: CallOptions & CallOptionsExt,
  ): Promise<FeedPreferencesResponse>;
  /** Get articles for a specific date */
  getDailyFeed(
    request: DeepPartial<GetDailyFeedRequest>,
    options?: CallOptions & CallOptionsExt,
  ): Promise<GetDailyFeedResponse>;
  /** Get dates that have articles for the calendar view */
  getFeedCalendarStatus(
    request: DeepPartial<GetFeedCalendarStatusRequest>,
    options?: CallOptions & CallOptionsExt,
  ): Promise<GetFeedCalendarStatusResponse>;
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

function toTimestamp(date: Date): Timestamp {
  const seconds = Math.trunc(date.getTime() / 1_000);
  const nanos = (date.getTime() % 1_000) * 1_000_000;
  return { seconds, nanos };
}

function fromTimestamp(t: Timestamp): Date {
  let millis = (t.seconds || 0) * 1_000;
  millis += (t.nanos || 0) / 1_000_000;
  return new globalThis.Date(millis);
}

function fromJsonTimestamp(o: any): Date {
  if (o instanceof globalThis.Date) {
    return o;
  } else if (typeof o === "string") {
    return new globalThis.Date(o);
  } else {
    return fromTimestamp(Timestamp.fromJSON(o));
  }
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create(base?: DeepPartial<T>): T;
  fromPartial(object: DeepPartial<T>): T;
}
