// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.8.3
//   protoc               v3.21.12
// source: proto/payment/payment.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import type { CallContext, CallOptions } from "nice-grpc-common";

export const protobufPackage = "payment";

export interface CreateSubscriptionOrderRequest {
  /** "PRO" or "FREE" (though free won't call this) */
  planId: string;
}

export interface CreateSubscriptionOrderResponse {
  orderId: string;
  amount: number;
  currency: string;
  keyId: string;
  paymentLink: string;
}

function createBaseCreateSubscriptionOrderRequest(): CreateSubscriptionOrderRequest {
  return { planId: "" };
}

export const CreateSubscriptionOrderRequest: MessageFns<CreateSubscriptionOrderRequest> = {
  encode(message: CreateSubscriptionOrderRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.planId !== "") {
      writer.uint32(10).string(message.planId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CreateSubscriptionOrderRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCreateSubscriptionOrderRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.planId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CreateSubscriptionOrderRequest {
    return { planId: isSet(object.planId) ? globalThis.String(object.planId) : "" };
  },

  toJSON(message: CreateSubscriptionOrderRequest): unknown {
    const obj: any = {};
    if (message.planId !== "") {
      obj.planId = message.planId;
    }
    return obj;
  },

  create(base?: DeepPartial<CreateSubscriptionOrderRequest>): CreateSubscriptionOrderRequest {
    return CreateSubscriptionOrderRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<CreateSubscriptionOrderRequest>): CreateSubscriptionOrderRequest {
    const message = createBaseCreateSubscriptionOrderRequest();
    message.planId = object.planId ?? "";
    return message;
  },
};

function createBaseCreateSubscriptionOrderResponse(): CreateSubscriptionOrderResponse {
  return { orderId: "", amount: 0, currency: "", keyId: "", paymentLink: "" };
}

export const CreateSubscriptionOrderResponse: MessageFns<CreateSubscriptionOrderResponse> = {
  encode(message: CreateSubscriptionOrderResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.orderId !== "") {
      writer.uint32(10).string(message.orderId);
    }
    if (message.amount !== 0) {
      writer.uint32(21).float(message.amount);
    }
    if (message.currency !== "") {
      writer.uint32(26).string(message.currency);
    }
    if (message.keyId !== "") {
      writer.uint32(34).string(message.keyId);
    }
    if (message.paymentLink !== "") {
      writer.uint32(42).string(message.paymentLink);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CreateSubscriptionOrderResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCreateSubscriptionOrderResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.orderId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 21) {
            break;
          }

          message.amount = reader.float();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.currency = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.keyId = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.paymentLink = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CreateSubscriptionOrderResponse {
    return {
      orderId: isSet(object.orderId) ? globalThis.String(object.orderId) : "",
      amount: isSet(object.amount) ? globalThis.Number(object.amount) : 0,
      currency: isSet(object.currency) ? globalThis.String(object.currency) : "",
      keyId: isSet(object.keyId) ? globalThis.String(object.keyId) : "",
      paymentLink: isSet(object.paymentLink) ? globalThis.String(object.paymentLink) : "",
    };
  },

  toJSON(message: CreateSubscriptionOrderResponse): unknown {
    const obj: any = {};
    if (message.orderId !== "") {
      obj.orderId = message.orderId;
    }
    if (message.amount !== 0) {
      obj.amount = message.amount;
    }
    if (message.currency !== "") {
      obj.currency = message.currency;
    }
    if (message.keyId !== "") {
      obj.keyId = message.keyId;
    }
    if (message.paymentLink !== "") {
      obj.paymentLink = message.paymentLink;
    }
    return obj;
  },

  create(base?: DeepPartial<CreateSubscriptionOrderResponse>): CreateSubscriptionOrderResponse {
    return CreateSubscriptionOrderResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<CreateSubscriptionOrderResponse>): CreateSubscriptionOrderResponse {
    const message = createBaseCreateSubscriptionOrderResponse();
    message.orderId = object.orderId ?? "";
    message.amount = object.amount ?? 0;
    message.currency = object.currency ?? "";
    message.keyId = object.keyId ?? "";
    message.paymentLink = object.paymentLink ?? "";
    return message;
  },
};

export interface PaymentServiceImplementation<CallContextExt = {}> {
  createSubscriptionOrder(
    request: CreateSubscriptionOrderRequest,
    context: CallContext & CallContextExt,
  ): Promise<DeepPartial<CreateSubscriptionOrderResponse>>;
}

export interface PaymentServiceClient<CallOptionsExt = {}> {
  createSubscriptionOrder(
    request: DeepPartial<CreateSubscriptionOrderRequest>,
    options?: CallOptions & CallOptionsExt,
  ): Promise<CreateSubscriptionOrderResponse>;
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create(base?: DeepPartial<T>): T;
  fromPartial(object: DeepPartial<T>): T;
}
