// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: backend/proto/feed/feed.proto

package feed

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UpdateFeedPreferencesRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	InterestPrompt string                 `protobuf:"bytes,1,opt,name=interest_prompt,json=interestPrompt,proto3" json:"interest_prompt,omitempty"`
	FeedEnabled    bool                   `protobuf:"varint,2,opt,name=feed_enabled,json=feedEnabled,proto3" json:"feed_enabled,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateFeedPreferencesRequest) Reset() {
	*x = UpdateFeedPreferencesRequest{}
	mi := &file_backend_proto_feed_feed_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateFeedPreferencesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateFeedPreferencesRequest) ProtoMessage() {}

func (x *UpdateFeedPreferencesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_backend_proto_feed_feed_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateFeedPreferencesRequest.ProtoReflect.Descriptor instead.
func (*UpdateFeedPreferencesRequest) Descriptor() ([]byte, []int) {
	return file_backend_proto_feed_feed_proto_rawDescGZIP(), []int{0}
}

func (x *UpdateFeedPreferencesRequest) GetInterestPrompt() string {
	if x != nil {
		return x.InterestPrompt
	}
	return ""
}

func (x *UpdateFeedPreferencesRequest) GetFeedEnabled() bool {
	if x != nil {
		return x.FeedEnabled
	}
	return false
}

type FeedPreferencesResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	InterestPrompt string                 `protobuf:"bytes,1,opt,name=interest_prompt,json=interestPrompt,proto3" json:"interest_prompt,omitempty"`
	FeedEnabled    bool                   `protobuf:"varint,2,opt,name=feed_enabled,json=feedEnabled,proto3" json:"feed_enabled,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *FeedPreferencesResponse) Reset() {
	*x = FeedPreferencesResponse{}
	mi := &file_backend_proto_feed_feed_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeedPreferencesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeedPreferencesResponse) ProtoMessage() {}

func (x *FeedPreferencesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_backend_proto_feed_feed_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeedPreferencesResponse.ProtoReflect.Descriptor instead.
func (*FeedPreferencesResponse) Descriptor() ([]byte, []int) {
	return file_backend_proto_feed_feed_proto_rawDescGZIP(), []int{1}
}

func (x *FeedPreferencesResponse) GetInterestPrompt() string {
	if x != nil {
		return x.InterestPrompt
	}
	return ""
}

func (x *FeedPreferencesResponse) GetFeedEnabled() bool {
	if x != nil {
		return x.FeedEnabled
	}
	return false
}

type GetDailyFeedRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Date in YYYY-MM-DD format
	Date          string `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDailyFeedRequest) Reset() {
	*x = GetDailyFeedRequest{}
	mi := &file_backend_proto_feed_feed_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDailyFeedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDailyFeedRequest) ProtoMessage() {}

func (x *GetDailyFeedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_backend_proto_feed_feed_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDailyFeedRequest.ProtoReflect.Descriptor instead.
func (*GetDailyFeedRequest) Descriptor() ([]byte, []int) {
	return file_backend_proto_feed_feed_proto_rawDescGZIP(), []int{2}
}

func (x *GetDailyFeedRequest) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

type Article struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title          string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Url            string                 `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	Snippet        string                 `protobuf:"bytes,4,opt,name=snippet,proto3" json:"snippet,omitempty"`
	RelevanceScore float32                `protobuf:"fixed32,5,opt,name=relevance_score,json=relevanceScore,proto3" json:"relevance_score,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Article) Reset() {
	*x = Article{}
	mi := &file_backend_proto_feed_feed_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Article) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Article) ProtoMessage() {}

func (x *Article) ProtoReflect() protoreflect.Message {
	mi := &file_backend_proto_feed_feed_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Article.ProtoReflect.Descriptor instead.
func (*Article) Descriptor() ([]byte, []int) {
	return file_backend_proto_feed_feed_proto_rawDescGZIP(), []int{3}
}

func (x *Article) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Article) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Article) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Article) GetSnippet() string {
	if x != nil {
		return x.Snippet
	}
	return ""
}

func (x *Article) GetRelevanceScore() float32 {
	if x != nil {
		return x.RelevanceScore
	}
	return 0
}

func (x *Article) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type GetDailyFeedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Date          string                 `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	Articles      []*Article             `protobuf:"bytes,2,rep,name=articles,proto3" json:"articles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDailyFeedResponse) Reset() {
	*x = GetDailyFeedResponse{}
	mi := &file_backend_proto_feed_feed_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDailyFeedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDailyFeedResponse) ProtoMessage() {}

func (x *GetDailyFeedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_backend_proto_feed_feed_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDailyFeedResponse.ProtoReflect.Descriptor instead.
func (*GetDailyFeedResponse) Descriptor() ([]byte, []int) {
	return file_backend_proto_feed_feed_proto_rawDescGZIP(), []int{4}
}

func (x *GetDailyFeedResponse) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *GetDailyFeedResponse) GetArticles() []*Article {
	if x != nil {
		return x.Articles
	}
	return nil
}

type GetFeedCalendarStatusRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Month in YYYY-MM format, defaults to current month
	Month         string `protobuf:"bytes,1,opt,name=month,proto3" json:"month,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFeedCalendarStatusRequest) Reset() {
	*x = GetFeedCalendarStatusRequest{}
	mi := &file_backend_proto_feed_feed_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFeedCalendarStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFeedCalendarStatusRequest) ProtoMessage() {}

func (x *GetFeedCalendarStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_backend_proto_feed_feed_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFeedCalendarStatusRequest.ProtoReflect.Descriptor instead.
func (*GetFeedCalendarStatusRequest) Descriptor() ([]byte, []int) {
	return file_backend_proto_feed_feed_proto_rawDescGZIP(), []int{5}
}

func (x *GetFeedCalendarStatusRequest) GetMonth() string {
	if x != nil {
		return x.Month
	}
	return ""
}

type CalendarDay struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Date          string                 `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	ArticleCount  int32                  `protobuf:"varint,2,opt,name=article_count,json=articleCount,proto3" json:"article_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CalendarDay) Reset() {
	*x = CalendarDay{}
	mi := &file_backend_proto_feed_feed_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalendarDay) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalendarDay) ProtoMessage() {}

func (x *CalendarDay) ProtoReflect() protoreflect.Message {
	mi := &file_backend_proto_feed_feed_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalendarDay.ProtoReflect.Descriptor instead.
func (*CalendarDay) Descriptor() ([]byte, []int) {
	return file_backend_proto_feed_feed_proto_rawDescGZIP(), []int{6}
}

func (x *CalendarDay) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *CalendarDay) GetArticleCount() int32 {
	if x != nil {
		return x.ArticleCount
	}
	return 0
}

type GetFeedCalendarStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Days          []*CalendarDay         `protobuf:"bytes,1,rep,name=days,proto3" json:"days,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFeedCalendarStatusResponse) Reset() {
	*x = GetFeedCalendarStatusResponse{}
	mi := &file_backend_proto_feed_feed_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFeedCalendarStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFeedCalendarStatusResponse) ProtoMessage() {}

func (x *GetFeedCalendarStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_backend_proto_feed_feed_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFeedCalendarStatusResponse.ProtoReflect.Descriptor instead.
func (*GetFeedCalendarStatusResponse) Descriptor() ([]byte, []int) {
	return file_backend_proto_feed_feed_proto_rawDescGZIP(), []int{7}
}

func (x *GetFeedCalendarStatusResponse) GetDays() []*CalendarDay {
	if x != nil {
		return x.Days
	}
	return nil
}

var File_backend_proto_feed_feed_proto protoreflect.FileDescriptor

const file_backend_proto_feed_feed_proto_rawDesc = "" +
	"\n" +
	"\x1dbackend/proto/feed/feed.proto\x12\x04feed\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"j\n" +
	"\x1cUpdateFeedPreferencesRequest\x12'\n" +
	"\x0finterest_prompt\x18\x01 \x01(\tR\x0einterestPrompt\x12!\n" +
	"\ffeed_enabled\x18\x02 \x01(\bR\vfeedEnabled\"e\n" +
	"\x17FeedPreferencesResponse\x12'\n" +
	"\x0finterest_prompt\x18\x01 \x01(\tR\x0einterestPrompt\x12!\n" +
	"\ffeed_enabled\x18\x02 \x01(\bR\vfeedEnabled\")\n" +
	"\x13GetDailyFeedRequest\x12\x12\n" +
	"\x04date\x18\x01 \x01(\tR\x04date\"\xbf\x01\n" +
	"\aArticle\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x10\n" +
	"\x03url\x18\x03 \x01(\tR\x03url\x12\x18\n" +
	"\asnippet\x18\x04 \x01(\tR\asnippet\x12'\n" +
	"\x0frelevance_score\x18\x05 \x01(\x02R\x0erelevanceScore\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"U\n" +
	"\x14GetDailyFeedResponse\x12\x12\n" +
	"\x04date\x18\x01 \x01(\tR\x04date\x12)\n" +
	"\barticles\x18\x02 \x03(\v2\r.feed.ArticleR\barticles\"4\n" +
	"\x1cGetFeedCalendarStatusRequest\x12\x14\n" +
	"\x05month\x18\x01 \x01(\tR\x05month\"F\n" +
	"\vCalendarDay\x12\x12\n" +
	"\x04date\x18\x01 \x01(\tR\x04date\x12#\n" +
	"\rarticle_count\x18\x02 \x01(\x05R\farticleCount\"F\n" +
	"\x1dGetFeedCalendarStatusResponse\x12%\n" +
	"\x04days\x18\x01 \x03(\v2\x11.feed.CalendarDayR\x04days2\xd8\x02\n" +
	"\vFeedService\x12S\n" +
	"\x15UpdateFeedPreferences\x12\".feed.UpdateFeedPreferencesRequest\x1a\x16.google.protobuf.Empty\x12K\n" +
	"\x12GetFeedPreferences\x12\x16.google.protobuf.Empty\x1a\x1d.feed.FeedPreferencesResponse\x12E\n" +
	"\fGetDailyFeed\x12\x19.feed.GetDailyFeedRequest\x1a\x1a.feed.GetDailyFeedResponse\x12`\n" +
	"\x15GetFeedCalendarStatus\x12\".feed.GetFeedCalendarStatusRequest\x1a#.feed.GetFeedCalendarStatusResponseB(Z&github.com/amityadav/landr/pkg/pb/feedb\x06proto3"

var (
	file_backend_proto_feed_feed_proto_rawDescOnce sync.Once
	file_backend_proto_feed_feed_proto_rawDescData []byte
)

func file_backend_proto_feed_feed_proto_rawDescGZIP() []byte {
	file_backend_proto_feed_feed_proto_rawDescOnce.Do(func() {
		file_backend_proto_feed_feed_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_backend_proto_feed_feed_proto_rawDesc), len(file_backend_proto_feed_feed_proto_rawDesc)))
	})
	return file_backend_proto_feed_feed_proto_rawDescData
}

var file_backend_proto_feed_feed_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_backend_proto_feed_feed_proto_goTypes = []any{
	(*UpdateFeedPreferencesRequest)(nil),  // 0: feed.UpdateFeedPreferencesRequest
	(*FeedPreferencesResponse)(nil),       // 1: feed.FeedPreferencesResponse
	(*GetDailyFeedRequest)(nil),           // 2: feed.GetDailyFeedRequest
	(*Article)(nil),                       // 3: feed.Article
	(*GetDailyFeedResponse)(nil),          // 4: feed.GetDailyFeedResponse
	(*GetFeedCalendarStatusRequest)(nil),  // 5: feed.GetFeedCalendarStatusRequest
	(*CalendarDay)(nil),                   // 6: feed.CalendarDay
	(*GetFeedCalendarStatusResponse)(nil), // 7: feed.GetFeedCalendarStatusResponse
	(*timestamppb.Timestamp)(nil),         // 8: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),                 // 9: google.protobuf.Empty
}
var file_backend_proto_feed_feed_proto_depIdxs = []int32{
	8, // 0: feed.Article.created_at:type_name -> google.protobuf.Timestamp
	3, // 1: feed.GetDailyFeedResponse.articles:type_name -> feed.Article
	6, // 2: feed.GetFeedCalendarStatusResponse.days:type_name -> feed.CalendarDay
	0, // 3: feed.FeedService.UpdateFeedPreferences:input_type -> feed.UpdateFeedPreferencesRequest
	9, // 4: feed.FeedService.GetFeedPreferences:input_type -> google.protobuf.Empty
	2, // 5: feed.FeedService.GetDailyFeed:input_type -> feed.GetDailyFeedRequest
	5, // 6: feed.FeedService.GetFeedCalendarStatus:input_type -> feed.GetFeedCalendarStatusRequest
	9, // 7: feed.FeedService.UpdateFeedPreferences:output_type -> google.protobuf.Empty
	1, // 8: feed.FeedService.GetFeedPreferences:output_type -> feed.FeedPreferencesResponse
	4, // 9: feed.FeedService.GetDailyFeed:output_type -> feed.GetDailyFeedResponse
	7, // 10: feed.FeedService.GetFeedCalendarStatus:output_type -> feed.GetFeedCalendarStatusResponse
	7, // [7:11] is the sub-list for method output_type
	3, // [3:7] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_backend_proto_feed_feed_proto_init() }
func file_backend_proto_feed_feed_proto_init() {
	if File_backend_proto_feed_feed_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_backend_proto_feed_feed_proto_rawDesc), len(file_backend_proto_feed_feed_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_backend_proto_feed_feed_proto_goTypes,
		DependencyIndexes: file_backend_proto_feed_feed_proto_depIdxs,
		MessageInfos:      file_backend_proto_feed_feed_proto_msgTypes,
	}.Build()
	File_backend_proto_feed_feed_proto = out.File
	file_backend_proto_feed_feed_proto_goTypes = nil
	file_backend_proto_feed_feed_proto_depIdxs = nil
}
