// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.0
// source: backend/proto/feed/feed.proto

package feed

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FeedService_UpdateFeedPreferences_FullMethodName = "/feed.FeedService/UpdateFeedPreferences"
	FeedService_GetFeedPreferences_FullMethodName    = "/feed.FeedService/GetFeedPreferences"
	FeedService_GetDailyFeed_FullMethodName          = "/feed.FeedService/GetDailyFeed"
	FeedService_GetFeedCalendarStatus_FullMethodName = "/feed.FeedService/GetFeedCalendarStatus"
)

// FeedServiceClient is the client API for FeedService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FeedServiceClient interface {
	// Update user's feed preferences (interest prompt and enable/disable)
	UpdateFeedPreferences(ctx context.Context, in *UpdateFeedPreferencesRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Get user's current feed preferences
	GetFeedPreferences(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*FeedPreferencesResponse, error)
	// Get articles for a specific date
	GetDailyFeed(ctx context.Context, in *GetDailyFeedRequest, opts ...grpc.CallOption) (*GetDailyFeedResponse, error)
	// Get dates that have articles for the calendar view
	GetFeedCalendarStatus(ctx context.Context, in *GetFeedCalendarStatusRequest, opts ...grpc.CallOption) (*GetFeedCalendarStatusResponse, error)
}

type feedServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFeedServiceClient(cc grpc.ClientConnInterface) FeedServiceClient {
	return &feedServiceClient{cc}
}

func (c *feedServiceClient) UpdateFeedPreferences(ctx context.Context, in *UpdateFeedPreferencesRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, FeedService_UpdateFeedPreferences_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *feedServiceClient) GetFeedPreferences(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*FeedPreferencesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FeedPreferencesResponse)
	err := c.cc.Invoke(ctx, FeedService_GetFeedPreferences_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *feedServiceClient) GetDailyFeed(ctx context.Context, in *GetDailyFeedRequest, opts ...grpc.CallOption) (*GetDailyFeedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDailyFeedResponse)
	err := c.cc.Invoke(ctx, FeedService_GetDailyFeed_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *feedServiceClient) GetFeedCalendarStatus(ctx context.Context, in *GetFeedCalendarStatusRequest, opts ...grpc.CallOption) (*GetFeedCalendarStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetFeedCalendarStatusResponse)
	err := c.cc.Invoke(ctx, FeedService_GetFeedCalendarStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FeedServiceServer is the server API for FeedService service.
// All implementations must embed UnimplementedFeedServiceServer
// for forward compatibility.
type FeedServiceServer interface {
	// Update user's feed preferences (interest prompt and enable/disable)
	UpdateFeedPreferences(context.Context, *UpdateFeedPreferencesRequest) (*emptypb.Empty, error)
	// Get user's current feed preferences
	GetFeedPreferences(context.Context, *emptypb.Empty) (*FeedPreferencesResponse, error)
	// Get articles for a specific date
	GetDailyFeed(context.Context, *GetDailyFeedRequest) (*GetDailyFeedResponse, error)
	// Get dates that have articles for the calendar view
	GetFeedCalendarStatus(context.Context, *GetFeedCalendarStatusRequest) (*GetFeedCalendarStatusResponse, error)
	mustEmbedUnimplementedFeedServiceServer()
}

// UnimplementedFeedServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFeedServiceServer struct{}

func (UnimplementedFeedServiceServer) UpdateFeedPreferences(context.Context, *UpdateFeedPreferencesRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateFeedPreferences not implemented")
}
func (UnimplementedFeedServiceServer) GetFeedPreferences(context.Context, *emptypb.Empty) (*FeedPreferencesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFeedPreferences not implemented")
}
func (UnimplementedFeedServiceServer) GetDailyFeed(context.Context, *GetDailyFeedRequest) (*GetDailyFeedResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDailyFeed not implemented")
}
func (UnimplementedFeedServiceServer) GetFeedCalendarStatus(context.Context, *GetFeedCalendarStatusRequest) (*GetFeedCalendarStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFeedCalendarStatus not implemented")
}
func (UnimplementedFeedServiceServer) mustEmbedUnimplementedFeedServiceServer() {}
func (UnimplementedFeedServiceServer) testEmbeddedByValue()                     {}

// UnsafeFeedServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FeedServiceServer will
// result in compilation errors.
type UnsafeFeedServiceServer interface {
	mustEmbedUnimplementedFeedServiceServer()
}

func RegisterFeedServiceServer(s grpc.ServiceRegistrar, srv FeedServiceServer) {
	// If the following call pancis, it indicates UnimplementedFeedServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FeedService_ServiceDesc, srv)
}

func _FeedService_UpdateFeedPreferences_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateFeedPreferencesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FeedServiceServer).UpdateFeedPreferences(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FeedService_UpdateFeedPreferences_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FeedServiceServer).UpdateFeedPreferences(ctx, req.(*UpdateFeedPreferencesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FeedService_GetFeedPreferences_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FeedServiceServer).GetFeedPreferences(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FeedService_GetFeedPreferences_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FeedServiceServer).GetFeedPreferences(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _FeedService_GetDailyFeed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDailyFeedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FeedServiceServer).GetDailyFeed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FeedService_GetDailyFeed_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FeedServiceServer).GetDailyFeed(ctx, req.(*GetDailyFeedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FeedService_GetFeedCalendarStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFeedCalendarStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FeedServiceServer).GetFeedCalendarStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FeedService_GetFeedCalendarStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FeedServiceServer).GetFeedCalendarStatus(ctx, req.(*GetFeedCalendarStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FeedService_ServiceDesc is the grpc.ServiceDesc for FeedService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FeedService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "feed.FeedService",
	HandlerType: (*FeedServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdateFeedPreferences",
			Handler:    _FeedService_UpdateFeedPreferences_Handler,
		},
		{
			MethodName: "GetFeedPreferences",
			Handler:    _FeedService_GetFeedPreferences_Handler,
		},
		{
			MethodName: "GetDailyFeed",
			Handler:    _FeedService_GetDailyFeed_Handler,
		},
		{
			MethodName: "GetFeedCalendarStatus",
			Handler:    _FeedService_GetFeedCalendarStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "backend/proto/feed/feed.proto",
}
