// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: backend/proto/payment/payment.proto

package payment_pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateSubscriptionOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlanId        string                 `protobuf:"bytes,1,opt,name=plan_id,json=planId,proto3" json:"plan_id,omitempty"` // "PRO" or "FREE" (though free won't call this)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSubscriptionOrderRequest) Reset() {
	*x = CreateSubscriptionOrderRequest{}
	mi := &file_backend_proto_payment_payment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSubscriptionOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSubscriptionOrderRequest) ProtoMessage() {}

func (x *CreateSubscriptionOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_backend_proto_payment_payment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSubscriptionOrderRequest.ProtoReflect.Descriptor instead.
func (*CreateSubscriptionOrderRequest) Descriptor() ([]byte, []int) {
	return file_backend_proto_payment_payment_proto_rawDescGZIP(), []int{0}
}

func (x *CreateSubscriptionOrderRequest) GetPlanId() string {
	if x != nil {
		return x.PlanId
	}
	return ""
}

type CreateSubscriptionOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Amount        float32                `protobuf:"fixed32,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency      string                 `protobuf:"bytes,3,opt,name=currency,proto3" json:"currency,omitempty"`
	KeyId         string                 `protobuf:"bytes,4,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	PaymentLink   string                 `protobuf:"bytes,5,opt,name=payment_link,json=paymentLink,proto3" json:"payment_link,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSubscriptionOrderResponse) Reset() {
	*x = CreateSubscriptionOrderResponse{}
	mi := &file_backend_proto_payment_payment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSubscriptionOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSubscriptionOrderResponse) ProtoMessage() {}

func (x *CreateSubscriptionOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_backend_proto_payment_payment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSubscriptionOrderResponse.ProtoReflect.Descriptor instead.
func (*CreateSubscriptionOrderResponse) Descriptor() ([]byte, []int) {
	return file_backend_proto_payment_payment_proto_rawDescGZIP(), []int{1}
}

func (x *CreateSubscriptionOrderResponse) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *CreateSubscriptionOrderResponse) GetAmount() float32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *CreateSubscriptionOrderResponse) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *CreateSubscriptionOrderResponse) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

func (x *CreateSubscriptionOrderResponse) GetPaymentLink() string {
	if x != nil {
		return x.PaymentLink
	}
	return ""
}

var File_backend_proto_payment_payment_proto protoreflect.FileDescriptor

const file_backend_proto_payment_payment_proto_rawDesc = "" +
	"\n" +
	"#backend/proto/payment/payment.proto\x12\apayment\"9\n" +
	"\x1eCreateSubscriptionOrderRequest\x12\x17\n" +
	"\aplan_id\x18\x01 \x01(\tR\x06planId\"\xaa\x01\n" +
	"\x1fCreateSubscriptionOrderResponse\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x02R\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x03 \x01(\tR\bcurrency\x12\x15\n" +
	"\x06key_id\x18\x04 \x01(\tR\x05keyId\x12!\n" +
	"\fpayment_link\x18\x05 \x01(\tR\vpaymentLink2~\n" +
	"\x0ePaymentService\x12l\n" +
	"\x17CreateSubscriptionOrder\x12'.payment.CreateSubscriptionOrderRequest\x1a(.payment.CreateSubscriptionOrderResponseB.Z,github.com/amityadav/landr/pkg/pb/payment_pbb\x06proto3"

var (
	file_backend_proto_payment_payment_proto_rawDescOnce sync.Once
	file_backend_proto_payment_payment_proto_rawDescData []byte
)

func file_backend_proto_payment_payment_proto_rawDescGZIP() []byte {
	file_backend_proto_payment_payment_proto_rawDescOnce.Do(func() {
		file_backend_proto_payment_payment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_backend_proto_payment_payment_proto_rawDesc), len(file_backend_proto_payment_payment_proto_rawDesc)))
	})
	return file_backend_proto_payment_payment_proto_rawDescData
}

var file_backend_proto_payment_payment_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_backend_proto_payment_payment_proto_goTypes = []any{
	(*CreateSubscriptionOrderRequest)(nil),  // 0: payment.CreateSubscriptionOrderRequest
	(*CreateSubscriptionOrderResponse)(nil), // 1: payment.CreateSubscriptionOrderResponse
}
var file_backend_proto_payment_payment_proto_depIdxs = []int32{
	0, // 0: payment.PaymentService.CreateSubscriptionOrder:input_type -> payment.CreateSubscriptionOrderRequest
	1, // 1: payment.PaymentService.CreateSubscriptionOrder:output_type -> payment.CreateSubscriptionOrderResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_backend_proto_payment_payment_proto_init() }
func file_backend_proto_payment_payment_proto_init() {
	if File_backend_proto_payment_payment_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_backend_proto_payment_payment_proto_rawDesc), len(file_backend_proto_payment_payment_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_backend_proto_payment_payment_proto_goTypes,
		DependencyIndexes: file_backend_proto_payment_payment_proto_depIdxs,
		MessageInfos:      file_backend_proto_payment_payment_proto_msgTypes,
	}.Build()
	File_backend_proto_payment_payment_proto = out.File
	file_backend_proto_payment_payment_proto_goTypes = nil
	file_backend_proto_payment_payment_proto_depIdxs = nil
}
